name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4+12

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
  http: ^1.1.0
  auto_route: ^9.2.2
  google_maps_flutter: ^2.10.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.6
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.2
  coupon_uikit: ^0.2.1
  gap: ^3.0.1
  u_credit_card:
    git:
      url: https://github.com/utpal-barman/u-credit-card-flutter.git
  barcode_widget: ^2.0.4
  dio: ^5.7.0
  equatable: ^2.0.5
  get_it: ^8.0.2
  shimmer: ^3.0.0
  super_cupertino_navigation_bar:
    git:
      url: https://github.com/Amrazyan/super_cupertino_navigation_bar
      ref: c03ead0
  auto_size_text: ^3.0.0
  permission_handler: ^11.3.1
  location: ^6.0.2
  flutter_keyboard_visibility: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  swipeable_page_route: ^0.4.4
  wolt_modal_sheet: ^0.9.4
  widget_and_text_animator: ^1.1.5
  sms_autofill: ^2.3.1
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  flutter_cupertino_datetime_picker: ^3.0.0
  widget_zoom: ^0.0.4
  fluttertoast: 8.2.12
  like_button: ^2.0.5
  flutter_widget_from_html: ^0.15.3
  connectivity_plus: ^6.1.1
  geolocator: ^13.0.2
  app_tracking_transparency: ^2.0.6
  maps_toolkit: ^3.0.0
  flutter_polyline_points: ^2.1.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.2.6

  

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"
  ios: true
  image_path: "assets/icons/icon_white.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/Illustration/
    - assets/flags/
    - assets/logo/


  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900