name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
  http: ^1.1.0
  auto_route: ^9.2.2
  google_maps_flutter: ^2.5.3
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.1.0
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.1
flutter:
  uses-material-design: true
