// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGvtnLvYkYM6uNEkHfeGYQdCY0kUk3oo',
    appId: '1:1054004577544:web:f1d8554920eba4682498bd',
    messagingSenderId: '1054004577544',
    projectId: 'orig-inn',
    authDomain: 'orig-inn.firebaseapp.com',
    storageBucket: 'orig-inn.firebasestorage.app',
    measurementId: 'G-GJ0GH2PCY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyWXwZfdli9_4DGjiMOzncvRDpH6eOpec',
    appId: '1:1054004577544:android:7ef04b66ea0f3d102498bd',
    messagingSenderId: '1054004577544',
    projectId: 'orig-inn',
    storageBucket: 'orig-inn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdS4s5YaDGo66DotZzjIw2o_5ljqFAkcc',
    appId: '1:1054004577544:ios:fc8827f7978840da2498bd',
    messagingSenderId: '1054004577544',
    projectId: 'orig-inn',
    storageBucket: 'orig-inn.firebasestorage.app',
    iosBundleId: 'com.imexpro.originn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdS4s5YaDGo66DotZzjIw2o_5ljqFAkcc',
    appId: '1:1054004577544:ios:7c16aa9a4a04e4152498bd',
    messagingSenderId: '1054004577544',
    projectId: 'orig-inn',
    storageBucket: 'orig-inn.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUGvtnLvYkYM6uNEkHfeGYQdCY0kUk3oo',
    appId: '1:1054004577544:web:87202bfa6db2edff2498bd',
    messagingSenderId: '1054004577544',
    projectId: 'orig-inn',
    authDomain: 'orig-inn.firebaseapp.com',
    storageBucket: 'orig-inn.firebasestorage.app',
    measurementId: 'G-JSPRXNYJ0R',
  );
}
